#include "add_dish.h"
#include "Dishs.h"
#include "ui_add_dish.h"

add_dish::add_dish(SQLserver &sql,QWidget *parent) :
    QWidget(parent),
    ui(new Ui::add_dish)
  /**
  * Auto generated by QT
  * This code is the constructor function of the UI
  * Auto input
  * Constructor Function
  */
{
    ui->setupUi(this);
    db=&sql;
    ui->pushButton->setEnabled(false);
    //connect
    connect(ui->lineEdit,SIGNAL(editingFinished()),this,SLOT(unlock_addDish()));
    connect(ui->lineEdit_2,SIGNAL(editingFinished()),this,SLOT(unlock_addDish()));
    connect(ui->lineEdit,SIGNAL(textChanged(QString)),this,SLOT(unlock_addDish()));
    connect(ui->lineEdit_2,SIGNAL(textChanged(QString)),this,SLOT(unlock_addDish()));
}

void add_dish::on_pushButton_clicked() {
    /**
     * Creator:黄志宏
     * No input
     * No output
    */
    QString Qname = ui->lineEdit->text();
    QString Qprice = ui->lineEdit_2->text();
    QString Qdescribe = ui->lineEdit_3->text();
    string name = Qname.toStdString();
    float price = Qprice.toFloat();
    string describe = Qdescribe.toStdString();

    Dishs::AddDish(price, name, describe, "null",*db);

    emit complete();

    this->close();
}

void add_dish::unlock_addDish(){
    /**
    * Creator:冯梓轩
    * "确定"按钮的解锁
    * No input
    * No output
    */
    if(ui->lineEdit->text()!=""&&
            ui->lineEdit_2->text()!=""&&
            ui->lineEdit_2->text().toFloat()>0){
        ui->pushButton->setEnabled(true);
    }else{
        ui->pushButton->setEnabled(false);
    }
}

void add_dish::on__back_clicked(){
    /**
    * Creator:冯梓轩
    * "取消"按钮
    * No input
    * No output
    */
    this->close();
}
add_dish::~add_dish()
/**
* Auto generated by QT
* This code is the destructor function of the UI
* No input
* Destructor Function
*/
{
    delete ui;
}
