#ifndef ADD_DISH_H
#define ADD_DISH_H
// writen by FZX(by QT);
// 这个文档是QT生成的窗体头文件.
#include <QWidget>
#include"SQLserver.h"
namespace Ui {
class add_dish;
}

class add_dish : public QWidget
{
    Q_OBJECT
signals:
    void complete();
public:
    /*
    * Auto generated by QT
    */
    explicit add_dish(SQLserver &sql,QWidget *parent = nullptr);/*Default constructor*/
    ~add_dish();/*Default destructor*/


private:
    /*
    * Auto generated by QT
    */
    Ui::add_dish *ui;

    SQLserver *db;
private slots:
    //作者:冯梓轩
    void unlock_addDish();
    //作者:黄志宏
    void on_pushButton_clicked();
    void on__back_clicked();

};

#endif // ADD_DISH_H
