#ifndef MAINWINDOW_H
#define MAINWINDOW_H
// writen by FZX(by QT);
// 这个文档是QT生成的窗体头文件.
#include <QMainWindow>
#include<QString>
#include<QStringList>
#include<QList>
#include<QPushButton>

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

#include"Dishs.h"
#include"Orders.h"
#include"create_order.h"
#include"modify_order.h"
#include"SQLserver.h"
#include"add_dish.h"
class MainWindow : public QMainWindow
{
	Q_OBJECT

public:
	/*
	* Auto generated by QT
	*/
	MainWindow(QWidget* parent = nullptr);/*Default constructor*/
	~MainWindow();/*Default destructor*/
private slots:
    /*
     * Here are the slot functions, they are used for buttons and other components of the window.
     */
    //作者:冯梓轩
    //按钮"创建订单"
    void on_new_order_clicked();

    //作者:冯梓轩
    //按钮"修改订单"
    void on_modify_order_clicked();

    //作者:冯梓轩
    //订单添加或修改
    void changedOrder(int id,bool find);

    //作者:冯梓轩
    //订单完成
    void finish_order(int id);

    //作者:冯梓轩
    //解锁"修改订单"
    void unlock_modify();

    //作者:黄志宏
    //"添加菜品"按钮
    void on_add_button_clicked();

    //作者:黄志宏
    //"删除菜品"按钮
    void on_remove_button_clicked();

    //作者:黄志宏
    //"调整菜品"按钮
    void modify_item(int ID);
private:
	/*
	* Auto generated by QT
	*/

    //作者:黄志宏
    //刷新菜单
    void info_show();

    /*
    * Auto generated by QT
    */
    Ui::MainWindow* ui;

    //作者:冯梓轩
    create_order* nwnd;
    mod_order* mnwnd;
    QList<QPushButton*> buttons;//buttons list

    //作者:李旭
    SQLserver sql;
};
#endif // MAINWINDOW_H
