#include "modify_dish.h"
#include "ui_modify_dish.h"
#include "Dishs.h"

modify_dish::modify_dish(SQLserver &sql,QWidget *parent, int ID) :
    QDialog(parent),
    ui(new Ui::modify_dish),
    ID(ID)
{
    /**
    * Auto generated by QT
    * This code is the constructor function of the UI
    * input:id of the dish to be modified
    * Constructor Function
    */
    ui->setupUi(this);
    ui->confirm->setEnabled(false);
    db=&sql;
    //connect
    connect(ui->lineEdit_2,SIGNAL(editingFinished()),this,SLOT(unlock_mod()));
    connect(ui->lineEdit_3,SIGNAL(editingFinished()),this,SLOT(unlock_mod()));
    connect(ui->lineEdit_2,SIGNAL(textChanged(QString)),this,SLOT(unlock_mod()));
    connect(ui->lineEdit_3,SIGNAL(textChanged(QString)),this,SLOT(unlock_mod()));

    //set text
    ui->lineEdit->setText(QString::fromStdString(Dishs::GetDish(this->ID).GetjpgPath()));
    ui->lineEdit_2->setText(QString::fromStdString(Dishs::GetDish(this->ID).Getname()));
    ui->lineEdit_3->setText(QString("%1").arg(Dishs::GetDish(this->ID).Getprice()));
    ui->lineEdit_4->setText(QString::fromStdString(Dishs::GetDish(this->ID).Getdescribe()));
    ui->onsell->setChecked(Dishs::GetDish(this->ID).getsell());
}

modify_dish::~modify_dish()
{
    delete ui;
}

void modify_dish::on_confirm_clicked() {
    /**
    * Author:黄志宏
    * "确定" button
    * No input
    * No output
    */
    QString Qjpg = ui->lineEdit->text();
    QString Qname = ui->lineEdit_2->text();
    QString Qprice = ui->lineEdit_3->text();
    QString Qdescribe = ui->lineEdit_4->text();

    string jpg = Qjpg.toStdString();
    string name = Qname.toStdString();
    float price = Qprice.toFloat();
    string describe = Qdescribe.toStdString();
    bool onsell = ui->onsell->checkState();

    Dishs::GetDish(this->ID).SetjpgPath(jpg);
    Dishs::GetDish(this->ID).Setname(name);
    Dishs::GetDish(this->ID).Setprice(price);
    Dishs::GetDish(this->ID).Setdescribe(describe);
    onsell ?
        Dishs::GetDish(this->ID).Onsell():
        Dishs::GetDish(this->ID).Unsell();
    db->reviseDish(Dishs::GetDish(this->ID));
    emit complete();
    this->close();
}

void modify_dish::on_exit_button_clicked() {
    /**
    * Author:黄志宏
    * "取消" button
    * No input
    * No output
    */
    this->close();
}

void modify_dish::unlock_mod(){
    /**
    * Author:冯梓轩
    * 控制"确定"按钮的可用状态
    * No input
    * No output
    */
    if(ui->lineEdit_2->text()!=""&&
            ui->lineEdit_3->text()!=""&&
            ui->lineEdit_3->text().toFloat()>0){
        ui->confirm->setEnabled(true);
    }else{
        ui->confirm->setEnabled(false);
    }
}
